# Generated by Django 5.2.6 on 2025-10-08 22:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ambiente',
            options={'ordering': ['nome'], 'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['-data_upload'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AlterModelOptions(
            name='ativo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterModelOptions(
            name='chamadoresponsavel',
            options={'ordering': ['-data_atribuicao'], 'verbose_name': 'Responsável do Chamado', 'verbose_name_plural': 'Responsáveis dos Chamados'},
        ),
        migrations.AlterModelOptions(
            name='chamadostatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de Status', 'verbose_name_plural': 'Histórico de Status'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='chamadostatushistory',
            name='descricao',
        ),
        migrations.AddField(
            model_name='anexo',
            name='usuario_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='ativos',
            field=models.ManyToManyField(blank=True, related_name='chamados', to='chamados.ativo'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadostatushistory',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nif',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='NIF/CPF'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to='anexos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamado'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='chamado_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados.chamadostatushistory'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='chamados.ambiente'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='codigo_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Patrimônio'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('inativo', 'Inativo'), ('descartado', 'Descartado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_sugerida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadoresponsavel',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='chamados.chamado'),
        ),
        migrations.AlterField(
            model_name='chamadoresponsavel',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamadoresponsavel',
            name='role',
            field=models.CharField(choices=[('responsavel_tecnico', 'Responsável Técnico'), ('supervisor', 'Supervisor'), ('colaborador', 'Colaborador')], default='responsavel_tecnico', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamadostatushistory',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado'),
        ),
        migrations.AlterField(
            model_name='chamadostatushistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['status', '-created_at'], name='chamados_ch_status_e3c268_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['urgencia'], name='chamados_ch_urgenci_b8a559_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['solicitante'], name='chamados_ch_solicit_f5f984_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadostatushistory',
            index=models.Index(fields=['chamado', '-created_at'], name='chamados_ch_chamado_ddf6ca_idx'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='chamados.categoria'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['codigo_patrimonio'], name='chamados_at_codigo__bbaf59_idx'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['status'], name='chamados_at_status_7b2cb2_idx'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida', '-created_at'], name='chamados_no_usuario_3fef74_idx'),
        ),
    ]
