# Generated by Django 5.2.6 on 2025-10-17 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_categoria_notificacao_alter_ambiente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='mimetype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='nome_arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tamanho_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='usuario_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
